# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:   
    adapter: postgresql  
    encoding: unicode  
    database: course_app
    pool: 5  
    timeout: 5000
    username: postgres

test:  
  adapter: postgresql  
  encoding: unicode  
  database: course_app  
  pool: 5  
  timeout: 5000
  username: postgres
